{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{*
 SOFTWARE NAME: eZchat
 SOFTWARE RELEASE: 0.1.x
 COPYRIGHT NOTICE: Copyright (C) 2008 Xavier GOULEY & Maxime THOMAS
 SOFTWARE LICENSE: GNU General Public License v2.0
 NOTICE: >
   This program is free software; you can redistribute it and/or
   modify it under the terms of version 2.0  of the GNU General
   Public License as published by the Free Software Foundation.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of version 2.0 of the GNU General
   Public License along with this program; if not, write to the Free
   Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
   MA 02110-1301, USA.
*}

{set-block scope=root variable=cache_ttl}0{/set-block}


<script src="{ezroot(no)}extension/ezchat/ajaxchat/js/chat.js" type="text/javascript" charset="UTF-8"></script>
<script src="{ezroot(no)}extension/ezchat/ajaxchat/js/logs.js" type="text/javascript" charset="UTF-8"></script>
<script src="{ezroot(no)}extension/ezchat/ajaxchat/js/lang/[LANG_CODE/].js" type="text/javascript" charset="UTF-8"></script>
<script src="{ezroot(no)}extension/ezchat/ajaxchat/js/config.js" type="text/javascript" charset="UTF-8"></script>
<script src="{ezroot(no)}extension/ezchat/ajaxchat/js/FABridge.js" type="text/javascript" charset="UTF-8"></script>
<script type="text/javascript">
	// <![CDATA[
		function toggleContainer(containerID, hideContainerIDs) {ldelim}
			if(hideContainerIDs) {ldelim}
				for(var i=0; i<hideContainerIDs.length; i++) {ldelim}
					ajaxChat.showHide(hideContainerIDs[i], 'none');
				{rdelim}
			{rdelim}
			ajaxChat.showHide(containerID);
			if(typeof arguments.callee.styleProperty == 'undefined') {ldelim}
				if(typeof isIElt7 != 'undefined') {ldelim}
					arguments.callee.styleProperty = 'marginRight';
				{rdelim} else {ldelim}
					arguments.callee.styleProperty = 'right';
				{rdelim}
			{rdelim}
			var containerWidth = document.getElementById(containerID).offsetWidth;
			if(containerWidth) {ldelim}
				document.getElementById('chatList').style[arguments.callee.styleProperty] = (containerWidth+28)+'px';
			{rdelim} else {ldelim}
				document.getElementById('chatList').style[arguments.callee.styleProperty] = '20px';
			{rdelim}
		{rdelim}

		function initialize() {ldelim}
			toggleContainer('settingsContainer');
			if(ajaxChat.getSetting('onlineList') === false) {ldelim}
				toggleContainer('onlineListContainer');
			{rdelim}
			ajaxChat.updateButton('audio', 'audioButton');
			ajaxChat.updateButton('autoScroll', 'autoScrollButton');
			document.getElementById('bbCodeSetting').checked = ajaxChat.getSetting('bbCode');
			document.getElementById('hyperLinksSetting').checked = ajaxChat.getSetting('hyperLinks');
			document.getElementById('lineBreaksSetting').checked = ajaxChat.getSetting('lineBreaks');
			document.getElementById('emoticonsSetting').checked = ajaxChat.getSetting('emoticons');
			document.getElementById('autoFocusSetting').checked = ajaxChat.getSetting('autoFocus');
			document.getElementById('maxMessagesSetting').value = ajaxChat.getSetting('maxMessages');
			document.getElementById('wordWrapSetting').checked = ajaxChat.getSetting('wordWrap');
			document.getElementById('maxWordLengthSetting').value = ajaxChat.getSetting('maxWordLength');
			document.getElementById('dateFormatSetting').value = ajaxChat.getSetting('dateFormat');
			document.getElementById('persistFontColorSetting').checked = ajaxChat.getSetting('persistFontColor');
			for(var i=0; i<document.getElementById('audioVolumeSetting').options.length; i++) {ldelim}
				if(document.getElementById('audioVolumeSetting').options[i].value == ajaxChat.getSetting('audioVolume')) {ldelim}
					document.getElementById('audioVolumeSetting').options[i].selected = true;
					break;
				{rdelim}
			{rdelim}
			ajaxChat.fillSoundSelection('soundReceiveSetting', ajaxChat.getSetting('soundReceive'));
			ajaxChat.fillSoundSelection('soundSendSetting', ajaxChat.getSetting('soundSend'));
			ajaxChat.fillSoundSelection('soundEnterSetting', ajaxChat.getSetting('soundEnter'));
			ajaxChat.fillSoundSelection('soundLeaveSetting', ajaxChat.getSetting('soundLeave'));
			ajaxChat.fillSoundSelection('soundChatBotSetting', ajaxChat.getSetting('soundChatBot'));
			ajaxChat.fillSoundSelection('soundErrorSetting', ajaxChat.getSetting('soundError'));
			document.getElementById('blinkSetting').checked = ajaxChat.getSetting('blink');
			document.getElementById('blinkIntervalSetting').value = ajaxChat.getSetting('blinkInterval');
			document.getElementById('blinkIntervalNumberSetting').value = ajaxChat.getSetting('blinkIntervalNumber');
		{rdelim}

		function finalize() {ldelim}
			ajaxChat.setSetting('onlineList', (document.getElementById('onlineListContainer').offsetWidth > 0));
		{rdelim}

		ajaxChatConfig.sessionName = '[SESSION_NAME/]';
		ajaxChatConfig.cookieExpiration = parseInt('[COOKIE_EXPIRATION/]');
		ajaxChatConfig.cookiePath = '[COOKIE_PATH/]';
		ajaxChatConfig.cookieDomain = '[COOKIE_DOMAIN/]';
		ajaxChatConfig.cookieSecure = '[COOKIE_SECURE/]';
		ajaxChatConfig.chatBotName = decodeURIComponent('[CHAT_BOT_NAME/]');
		ajaxChatConfig.chatBotID = '[CHAT_BOT_ID/]';
		ajaxChatConfig.allowUserMessageDelete = parseInt('[ALLOW_USER_MESSAGE_DELETE/]');
		ajaxChatConfig.inactiveTimeout = parseInt('[INACTIVE_TIMEOUT/]');
		ajaxChatConfig.privateChannelDiff = parseInt('[PRIVATE_CHANNEL_DIFF/]');
		ajaxChatConfig.privateMessageDiff = parseInt('[PRIVATE_MESSAGE_DIFF/]');
		ajaxChatConfig.showChannelMessages = true;
		ajaxChatConfig.messageTextMaxLength = parseInt('[MESSAGE_TEXT_MAX_LENGTH/]');
		ajaxChatConfig.socketServerEnabled = parseInt('[SOCKET_SERVER_ENABLED/]');
		ajaxChatConfig.socketServerHost = decodeURIComponent('[SOCKET_SERVER_HOST/]');
		ajaxChatConfig.socketServerPort = parseInt('[SOCKET_SERVER_PORT/]');
		ajaxChatConfig.socketServerChatID = parseInt('[SOCKET_SERVER_CHAT_ID/]');

		ajaxChatConfig.ajaxURL += '&view=logs';

		ajaxChatConfig.domIDs['yearSelection'] = 'yearSelection';
		ajaxChatConfig.domIDs['monthSelection'] = 'monthSelection';
		ajaxChatConfig.domIDs['daySelection'] = 'daySelection';
		ajaxChatConfig.domIDs['hourSelection'] = 'hourSelection';

		ajaxChatConfig.settings.dateFormat = '(%Y.%m.%d - %H:%i:%s)';
		ajaxChatConfig.settings.audio = false;
		ajaxChatConfig.settings.blink = false;
		ajaxChatConfig.nonPersistentSettings.push('dateFormat','audio','blink');


		ajaxChatConfig.ajaxURL = "{$loginURL|ezurl(no)}?ajax=true";
		ajaxChat.ajaxURL = "{$loginURL|ezurl(no)}?ajax=true";
 		ajaxChatConfig.baseURL = "{ezroot(no)}extension/ezchat/ajaxchat/";

		ajaxChat.init(ajaxChatConfig, ajaxChatLang, true, true, true, initialize, finalize);
	// ]]>
</script>


<div style="float:left;width:70%;">
	<div class="border-box">
	<div class="border-tl"><div class="border-tr"><div class="border-tc"></div></div></div>
	<div class="border-ml"><div class="border-mr"><div class="border-mc float-break">
	<div class="content-view-full">

			<div class="maincontentheader">
				<h1>[LANG]logsTitle[/LANG]</h1>
			</div>
			<div class="chatBlock">
				<div id="optionsContainer">
					<input type="button" class="defaultbutton" id="audioButton" value="[LANG]toggleAudio[/LANG]" title="[LANG]toggleAudio[/LANG]" onclick="ajaxChat.toggleSetting('audio', 'audioButton');"/>
					<input type="button" class="defaultbutton" id="autoScrollButton" value="[LANG]toggleAutoScroll[/LANG]" title="[LANG]toggleAutoScroll[/LANG]" onclick="ajaxChat.toggleSetting('autoScroll', 'autoScrollButton');"/>
		  		</div>
				<div id="chatList"></div>
				<div id="submitButtonContainer" class="buttonblock">
					<input class="defaultbutton" type="button" id="submitButton" value="[LANG]logsSearch[/LANG]" onclick="ajaxChat.sendMessage();"/>
				</div>
				<div id="inputFieldContainer">
					<textarea id="inputField" rows="2" wrap="soft" title="[LANG]inputLineBreak[/LANG]" onkeypress="ajaxChat.handleInputFieldKeyPress(event);"></textarea>
				</div>
				<div class="break"></div>
		  	</div>

	</div>
	</div></div></div>
	<div class="border-bl"><div class="border-br"><div class="border-bc"></div></div></div>
	</div>
</div>
<div style="float:right;width:30%;">
	<div class="border-box">
	<div class="border-tl"><div class="border-tr"><div class="border-tc"></div></div></div>
	<div class="border-ml"><div class="border-mr"><div class="border-mc" style="padding:0pt;">
	<div class="border-content">
		<div class="block-type-3items block-view-3_items1">
			<div class="attribute-header"><h2>[LANG]channel[/LANG]</h2></div>
			<div id="logoutChannelContainer" class="buttonblock">
				<div class="defaultselect">
					<select id="channelSelection" onchange="ajaxChat.getLogs();">[LOGS_CHANNEL_OPTIONS/]</select>
					<label for="yearSelection">[LANG]logsDate[/LANG]:</label>
					<select id="yearSelection" onchange="ajaxChat.getLogs();">[LOGS_YEAR_OPTIONS/]</select>
					<select id="monthSelection" onchange="ajaxChat.getLogs();">[LOGS_MONTH_OPTIONS/]</select>
					<select id="daySelection" onchange="ajaxChat.getLogs();">[LOGS_DAY_OPTIONS/]</select>
					<label for="hourSelection">[LANG]logsTime[/LANG]:</label>
					<select id="hourSelection" onchange="ajaxChat.getLogs();">[LOGS_HOUR_OPTIONS/]</select>
				</div>
				<div class="block-separator"></div>
				<input class="defaultbutton" type="button" id="logoutButton" value="{'Sign out from channel'|i18n('design/standard/ezchat','Button')}" onclick="ajaxChat.logout();"/>
	  		</div>
	  	</div>
		<div class="block-separator"></div>

	    <!-- BLOCK: START -->
		<div class="block-type-itemlist">
			<div class="attribute-header"><a href="#" title="[LANG]toggleSettings[/LANG]" onclick="toggleContainer('settingsContainer', new Array('onlineListContainer','helpContainer'));">
			    <h2>[LANG]settings[/LANG]</h2>
			</a></div>
			<div class="block-content" id="settingsContainer" style="display:none;">
			    <div id="settingsList">
					<table>
						<tr class="rowOdd">
							<td><label for="bbCodeSetting">[LANG]settingsBBCode[/LANG]</label></td>
							<td class="setting"><input type="checkbox" id="bbCodeSetting" onclick="ajaxChat.setSetting('bbCode', this.checked);"/></td>
						</tr>
						<tr class="rowEven">
							<td><label for="hyperLinksSetting">[LANG]settingsHyperLinks[/LANG]</label></td>
							<td class="setting"><input type="checkbox" id="hyperLinksSetting" onclick="ajaxChat.setSetting('hyperLinks', this.checked);"/></td>
						</tr>
						<tr class="rowOdd">
							<td><label for="lineBreaksSetting">[LANG]settingsLineBreaks[/LANG]</label></td>
							<td class="setting"><input type="checkbox" id="lineBreaksSetting" onclick="ajaxChat.setSetting('lineBreaks', this.checked);"/></td>
						</tr>
						<tr class="rowEven">
							<td><label for="emoticonsSetting">[LANG]settingsEmoticons[/LANG]</label></td>
							<td class="setting"><input type="checkbox" id="emoticonsSetting" onclick="ajaxChat.setSetting('emoticons', this.checked);"/></td>
						</tr>
						<tr class="rowOdd">
							<td><label for="autoFocusSetting">[LANG]settingsAutoFocus[/LANG]</label></td>
							<td class="setting"><input type="checkbox" id="autoFocusSetting" onclick="ajaxChat.setSetting('autoFocus', this.checked);"/></td>
						</tr>
						<tr class="rowEven">
							<td><label for="maxMessagesSetting">[LANG]settingsMaxMessages[/LANG]</label></td>
							<td class="setting"><input type="text" class="text" id="maxMessagesSetting" onchange="ajaxChat.setSetting('maxMessages', parseInt(this.value));"/></td>
						</tr>
						<tr class="rowOdd">
							<td><label for="wordWrapSetting">[LANG]settingsWordWrap[/LANG]</label></td>
							<td class="setting"><input type="checkbox" id="wordWrapSetting" onclick="ajaxChat.setSetting('wordWrap', this.checked);"/></td>
						</tr>
						<tr class="rowEven">
							<td><label for="maxWordLengthSetting">[LANG]settingsMaxWordLength[/LANG]</label></td>
							<td class="setting"><input type="text" class="text" id="maxWordLengthSetting" onchange="ajaxChat.setSetting('maxWordLength', parseInt(this.value));"/></td>
						</tr>
						<tr class="rowOdd">
							<td><label for="dateFormatSetting">[LANG]settingsDateFormat[/LANG]</label></td>
							<td class="setting"><input type="text" class="text" id="dateFormatSetting" onchange="ajaxChat.setSetting('dateFormat', this.value);"/></td>
						</tr>
						<tr class="rowEven">
							<td><label for="persistFontColorSetting">[LANG]settingsPersistFontColor[/LANG]</label></td>
							<td class="setting"><input type="checkbox" id="persistFontColorSetting" onclick="ajaxChat.setPersistFontColor(this.checked);"/></td>
						</tr>
						<tr class="rowOdd">
							<td><label for="audioVolumeSetting">[LANG]settingsAudioVolume[/LANG]</label></td>
							<td class="setting">
								<select class="left" id="audioVolumeSetting" onchange="ajaxChat.setAudioVolume(this.options[this.selectedIndex].value);">
									<option value="1.0">100 %</option>
									<option value="0.9">90 %</option>
									<option value="0.8">80 %</option>
									<option value="0.7">70 %</option>
									<option value="0.6">60 %</option>
									<option value="0.5">50 %</option>
									<option value="0.4">40 %</option>
									<option value="0.3">30 %</option>
									<option value="0.2">20 %</option>
									<option value="0.1">10 %</option>
								</select>
							</td>
						</tr>
						<tr class="rowEven">
							<td><label for="soundReceiveSetting">[LANG]settingsSoundReceive[/LANG]</label></td>
							<td class="setting">
								<select id="soundReceiveSetting" onchange="ajaxChat.setSetting('soundReceive', this.options[this.selectedIndex].value);"><option value="">-</option></select><input type="image" src="img/pixel.gif" class="button playback" alt="[LANG]playSelectedSound[/LANG]" title="[LANG]playSelectedSound[/LANG]" onclick="ajaxChat.playSound(this.previousSibling.options[this.previousSibling.selectedIndex].value);"/>
							</td>
						</tr>
						<tr class="rowOdd">
							<td><label for="soundSendSetting">[LANG]settingsSoundSend[/LANG]</label></td>
							<td class="setting">
								<select id="soundSendSetting" onchange="ajaxChat.setSetting('soundSend', this.options[this.selectedIndex].value);"><option value="">-</option></select><input type="image" src="img/pixel.gif" class="button playback" alt="[LANG]playSelectedSound[/LANG]" title="[LANG]playSelectedSound[/LANG]" onclick="ajaxChat.playSound(this.previousSibling.options[this.previousSibling.selectedIndex].value);"/>
							</td>
						</tr>
						<tr class="rowEven">
							<td><label for="soundEnterSetting">[LANG]settingsSoundEnter[/LANG]</label></td>
							<td class="setting">
								<select id="soundEnterSetting" onchange="ajaxChat.setSetting('soundEnter', this.options[this.selectedIndex].value);"><option value="">-</option></select><input type="image" src="img/pixel.gif" class="button playback" alt="[LANG]playSelectedSound[/LANG]" title="[LANG]playSelectedSound[/LANG]" onclick="ajaxChat.playSound(this.previousSibling.options[this.previousSibling.selectedIndex].value);"/>
							</td>
						</tr>
						<tr class="rowOdd">
							<td><label for="soundLeaveSetting">[LANG]settingsSoundLeave[/LANG]</label></td>
							<td class="setting">
								<select id="soundLeaveSetting" onchange="ajaxChat.setSetting('soundLeave', this.options[this.selectedIndex].value);"><option value="">-</option></select><input type="image" src="img/pixel.gif" class="button playback" alt="[LANG]playSelectedSound[/LANG]" title="[LANG]playSelectedSound[/LANG]" onclick="ajaxChat.playSound(this.previousSibling.options[this.previousSibling.selectedIndex].value);"/>
							</td>
						</tr>
						<tr class="rowEven">
							<td><label for="soundChatBotSetting">[LANG]settingsSoundChatBot[/LANG]</label></td>
							<td class="setting">
								<select id="soundChatBotSetting" onchange="ajaxChat.setSetting('soundChatBot', this.options[this.selectedIndex].value);"><option value="">-</option></select><input type="image" src="img/pixel.gif" class="button playback" alt="[LANG]playSelectedSound[/LANG]" title="[LANG]playSelectedSound[/LANG]" onclick="ajaxChat.playSound(this.previousSibling.options[this.previousSibling.selectedIndex].value);"/>
							</td>
						</tr>
						<tr class="rowOdd">
							<td><label for="soundErrorSetting">[LANG]settingsSoundError[/LANG]</label></td>
							<td class="setting">
								<select id="soundErrorSetting" onchange="ajaxChat.setSetting('soundError', this.options[this.selectedIndex].value);"><option value="">-</option></select><input type="image" src="img/pixel.gif" class="button playback" alt="[LANG]playSelectedSound[/LANG]" title="[LANG]playSelectedSound[/LANG]" onclick="ajaxChat.playSound(this.previousSibling.options[this.previousSibling.selectedIndex].value);"/>
							</td>
						</tr>
						<tr class="rowEven">
							<td><label for="blinkSetting">[LANG]settingsBlink[/LANG]</label></td>
							<td class="setting"><input type="checkbox" id="blinkSetting" onclick="ajaxChat.setSetting('blink', this.checked);"/></td>
						</tr>
						<tr class="rowOdd">
							<td><label for="blinkIntervalSetting">[LANG]settingsBlinkInterval[/LANG]</label></td>
							<td class="setting"><input type="text" class="text" id="blinkIntervalSetting" onchange="ajaxChat.setSetting('blinkInterval', parseInt(this.value));"/></td>
						</tr>
						<tr class="rowEven">
							<td><label for="blinkIntervalNumberSetting">[LANG]settingsBlinkIntervalNumber[/LANG]</label></td>
							<td class="setting"><input type="text" class="text" id="blinkIntervalNumberSetting" onchange="ajaxChat.setSetting('blinkIntervalNumber', parseInt(this.value));"/></td>
						</tr>
					</table>
				</div>
			</div>
		</div>
		<!-- BLOCK: END -->

		<div class="block-separator"></div>
		<!--
			Please retain the full copyright notice below including the link to blueimp.net.
			This not only gives respect to the amount of time given freely by the developer
			but also helps build interest, traffic and use of AJAX Chat.

			Thanks,
			Sebastian Tschan
		//-->
		<div class="chatCopyright"><a href="https://blueimp.net/ajax/">AJAX Chat</a> &copy; <a href="https://blueimp.net">blueimp.net</a></div>
	</div></div>
	</div></div></div>
	<div class="border-bl"><div class="border-br"><div class="border-bc"></div></div></div>
</div>
<div id="flashInterfaceContainer"></div>
