{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{*
 SOFTWARE NAME: eZchat
 SOFTWARE RELEASE: 0.1.x
 COPYRIGHT NOTICE: Copyright (C) 2008 Xavier GOULEY & Maxime THOMAS
 SOFTWARE LICENSE: GNU General Public License v2.0
 NOTICE: >
   This program is free software; you can redistribute it and/or
   modify it under the terms of version 2.0  of the GNU General
   Public License as published by the Free Software Foundation.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of version 2.0 of the GNU General
   Public License along with this program; if not, write to the Free
   Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
   MA 02110-1301, USA.
*}

<div id="ajaxChatContent">
	<script src="{ezroot(no)}extension/ezchat/ajaxchat/js/chat.js" type="text/javascript" charset="UTF-8"></script>
	<script src="{ezroot(no)}extension/ezchat/ajaxchat/js/custom.js" type="text/javascript" charset="UTF-8"></script>
	<script src="{ezroot(no)}extension/ezchat/ajaxchat/js/shoutbox.js" type="text/javascript" charset="UTF-8"></script>
	<script src="{ezroot(no)}extension/ezchat/ajaxchat/js/lang/[LANG_CODE/].js" type="text/javascript" charset="UTF-8"></script>
	<script src="{ezroot(no)}extension/ezchat/ajaxchat/js/config.js" type="text/javascript" charset="UTF-8"></script>
	<script src="{ezroot(no)}extension/ezchat/ajaxchat/js/FABridge.js" type="text/javascript" charset="UTF-8"></script>
	<div id="ajaxChatChatList"></div>
	<div id="ajaxChatInputFieldContainer">
		<input id="ajaxChatInputField" type="text" maxlength="[MESSAGE_TEXT_MAX_LENGTH/]" onkeypress="ajaxChat.handleInputFieldKeyPress(event);"/>
	</div>
	<script type="text/javascript">
		// <![CDATA[
			ajaxChatConfig.ajaxURL = "{$loginURL|ezurl(no)}?ajax=true&shoutbox=true";
			ajaxChatConfig.baseURL = "{ezroot(no)}extension/ezchat/ajaxchat/";

			ajaxChatConfig.sessionName = '[SESSION_NAME/]';
			ajaxChatConfig.cookieExpiration = parseInt('[COOKIE_EXPIRATION/]');
			ajaxChatConfig.cookiePath = '[COOKIE_PATH/]';
			ajaxChatConfig.cookieDomain = '[COOKIE_DOMAIN/]';
			ajaxChatConfig.cookieSecure = '[COOKIE_SECURE/]';
			ajaxChatConfig.chatBotName = decodeURIComponent('[CHAT_BOT_NAME/]');
			ajaxChatConfig.chatBotID = '[CHAT_BOT_ID/]';
			ajaxChatConfig.inactiveTimeout = parseInt('[INACTIVE_TIMEOUT/]');
			ajaxChatConfig.privateChannelDiff = parseInt('[PRIVATE_CHANNEL_DIFF/]');
			ajaxChatConfig.privateMessageDiff = parseInt('[PRIVATE_MESSAGE_DIFF/]');
			ajaxChatConfig.showChannelMessages = false;
			ajaxChatConfig.messageTextMaxLength = parseInt('[MESSAGE_TEXT_MAX_LENGTH/]');
			ajaxChatConfig.socketServerEnabled = parseInt('[SOCKET_SERVER_ENABLED/]');
			ajaxChatConfig.socketServerHost = decodeURIComponent('[SOCKET_SERVER_HOST/]');
			ajaxChatConfig.socketServerPort = parseInt('[SOCKET_SERVER_PORT/]');

			ajaxChatConfig.domIDs['chatList'] = 'ajaxChatChatList';
			ajaxChatConfig.domIDs['inputField'] = 'ajaxChatInputField';
			ajaxChatConfig.domIDs['flashInterfaceContainer'] = 'ajaxChatFlashInterfaceContainer';

			ajaxChatConfig.settings.autoFocus = false;
			ajaxChatConfig.settings.wordWrap = true;
			ajaxChatConfig.settings.maxWordLength = 11;
			ajaxChatConfig.settings.blink = false;
			ajaxChatConfig.nonPersistentSettings.push('autoFocus','wordWrap','maxWordLength','blink');

			ajaxChat.ajaxURL = "{$loginURL|ezurl(no)}?ajax=true";

			ajaxChat.init(ajaxChatConfig, ajaxChatLang, true, false, true);
		// ]]>
	</script>
	<!--
		Please retain the full copyright notice below including the link to blueimp.net.
		This not only gives respect to the amount of time given freely by the developer
		but also helps build interest, traffic and use of AJAX Chat.

		Thanks,
		Sebastian Tschan
	//-->
	<div id="ajaxChatCopyright"><a href="https://blueimp.net/ajax/">AJAX Chat</a> &copy; <a href="https://blueimp.net">blueimp.net</a></div>
</div>
<div id="ajaxChatFlashInterfaceContainer"></div>