{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{*
 SOFTWARE NAME: eZchat
 SOFTWARE RELEASE: 0.1.x
 COPYRIGHT NOTICE: Copyright (C) 2008 Xavier GOULEY & Maxime THOMAS
 SOFTWARE LICENSE: GNU General Public License v2.0
 NOTICE: >
   This program is free software; you can redistribute it and/or
   modify it under the terms of version 2.0  of the GNU General
   Public License as published by the Free Software Foundation.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of version 2.0 of the GNU General
   Public License along with this program; if not, write to the Free
   Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
   MA 02110-1301, USA.
*}

{* Because chatroom cannot be cached *}
{set-block scope=root variable=cache_ttl}0{/set-block}

{* Quick help with this attribute:
*
* channel name : {$attribute.content.name}
* Allow private messages : {$attribute.content.option_list.0.value} (0,1)
* Show channel messages : {$attribute.content.option_list.1.value} (0,1)
* Request messages prior channel enter : {$attribute.content.option_list.2.value} (0,1)
* Opened from {$attribute.content.start_value} to {$attribute.content.stop_value}
* Opening days (array 0->6) {$attribute.content.option_list.3.value|explode('-')}
* allowprivatechannels : {$attribute.contentclass_attribute.data_int1}
* allowusermessagedelete : {$attribute.contentclass_attribute.data_int2}
*}

{default shoutbox = false()}

{section show=$shoutbox}
	{$attribute.content.shoutbox}
{section-else}
	{$attribute.content.chatroom}
{/section}

{/default}