{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{*
 SOFTWARE NAME: eZchat
 SOFTWARE RELEASE: 0.1.x
 COPYRIGHT NOTICE: Copyright (C) 2008 Xavier GOULEY & Maxime THOMAS
 SOFTWARE LICENSE: GNU General Public License v2.0
 NOTICE: >
   This program is free software; you can redistribute it and/or
   modify it under the terms of version 2.0  of the GNU General
   Public License as published by the Free Software Foundation.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of version 2.0 of the GNU General
   Public License along with this program; if not, write to the Free
   Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
   MA 02110-1301, USA.
*}

<div class="block inline">
	<div class="element">
		{'Channel name'|i18n( 'ezchat/datatypes/chatroom' )}:
		{$attribute.content.name}
	</div>
	<div class="element">
		{'Allow private messages'|i18n( 'ezchat/datatypes/chatroom' )}:
		{$attribute.content.option_list.0.value||choose( 'No'|i18n( 'design/standard/content/datatype' ), 'Yes'|i18n( 'design/standard/content/datatype') )}
	</div>
	<div class="element">
		{'Show channel messages'|i18n( 'ezchat/datatypes/chatroom' )}:
		{$attribute.content.option_list.1.value||choose( 'No'|i18n( 'design/standard/content/datatype' ), 'Yes'|i18n( 'design/standard/content/datatype') )}
	</div>
	<div class="element">
		{'Request messages prior channel enter'|i18n( 'ezchat/datatypes/chatroom' )}:
		{$attribute.content.option_list.2.value||choose( 'No'|i18n( 'design/standard/content/datatype' ), 'Yes'|i18n( 'design/standard/content/datatype') )}
	</div>
</div>

<div class="block inline">
	<div class="element">
		{'Opened from %1h00 to %2h00.'|i18n( 'ezchat/datatypes/chatroom', '', array($attribute.content.start_value, $attribute.content.stop_value) )}
	</div>
	<div class="element">
		{'Opening days'|i18n( 'ezchat/datatypes/chatroom' )}:
		{foreach $attribute.content.option_list.3.value|explode('-') as $item}
			{array(	'Sunday'|i18n( 'ezchat/datatypes/chatroom'),
					'Monday'|i18n( 'ezchat/datatypes/chatroom'),
					'Tuesday'|i18n( 'ezchat/datatypes/chatroom'),
					'Wednesday'|i18n( 'ezchat/datatypes/chatroom'),
					'Thursday'|i18n( 'ezchat/datatypes/chatroom'),
					'Friday'|i18n( 'ezchat/datatypes/chatroom'),
					'Saturday'|i18n( 'ezchat/datatypes/chatroom') ).$item}
			{delimiter}, {/delimiter}
		{/foreach}
	</div>
</div>

<div class="break"></div>

