{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{*
 SOFTWARE NAME: eZchat
 SOFTWARE RELEASE: 0.1.x
 COPYRIGHT NOTICE: Copyright (C) 2008 Xavier GOULEY & Maxime THOMAS
 SOFTWARE LICENSE: GNU General Public License v2.0
 NOTICE: >
   This program is free software; you can redistribute it and/or
   modify it under the terms of version 2.0  of the GNU General
   Public License as published by the Free Software Foundation.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of version 2.0 of the GNU General
   Public License along with this program; if not, write to the Free
   Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
   MA 02110-1301, USA.
*}

{default attribute_base='ContentObjectAttribute'
         html_class='half'}
{let start_hour=$attribute.content.start_value}
{let stop_hour=$attribute.content.stop_value}
{let days=$attribute.content.option_list.3.value|explode('-')}

<div class="block">
<fieldset>
	<legend>
		<label>{'Channel name'|i18n( 'ezchat/datatypes/chatroom' )}:
			<input id="ezcoa-{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}" class="{eq( $html_class, 'half' )|choose( 'box', 'halfbox' )} ezcc-{$attribute.object.content_class.identifier} ezcca-{$attribute.object.content_class.identifier}_{$attribute.contentclass_attribute_identifier}" type="text" size="70" name="{$attribute_base}_ezchatroom_data_text_{$attribute.id}" value="{$attribute.content.name}" />
			{'(without special character)'|i18n( 'ezchat/datatypes/chatroom' )}
		</label>
	</legend>
	<div class="block inline">

		<div class="break"></div>

		<table class="list" style="width:400px" cellspacing="0">
			<tbody>
				<tr>
				    <th>{'Opening hours'|i18n( 'ezchat/datatypes/chatroom' )}</th>
				    <th>{'Opening days'|i18n( 'ezchat/datatypes/chatroom' )}</th>
				    <th>{'Messaging parameters'|i18n( 'ezchat/datatypes/chatroom' )}</th>
				</tr>
				<tr class="bglight">
					<td>
						<input type="hidden" name="{$attribute_base}_ezchatroom_hours_array_{$attribute.id}" value="" />
						<select id="ezcoa-{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}" class="ezcc-{$attribute.object.content_class.identifier} ezcca-{$attribute.object.content_class.identifier}_{$attribute.contentclass_attribute_identifier}" name="{$attribute_base}_ezchatroom_hours_array_{$attribute.id}[]" size="6" multiple="multiple">
							{section loop=array('00','01','02','03','04','05','06','07','08','09',10,11,12,13,14,15,16,17,18,19,20,21,22,23)}
								<option value="{$:item}" {section show=and( $start_hour|le($:item), $stop_hour|gt($:item) )}selected="selected"{/section}>{$:item} h</option>
							{/section}
						</select>
					</td>
					<td>
						<input type="hidden" name="{$attribute_base}_ezchatroom_days_array_{$attribute.id}" value="" />
						<select id="ezcoa-{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}" class="ezcc-{$attribute.object.content_class.identifier} ezcca-{$attribute.object.content_class.identifier}_{$attribute.contentclass_attribute_identifier}" name="{$attribute_base}_ezchatroom_days_array_{$attribute.id}[]" size="6" multiple="multiple">
							<option value="0" {section show=$days|contains('0')}selected="selected"{/section}>{'Sunday'|i18n( 'ezchat/datatypes/chatroom' )}</option>
							<option value="1" {section show=$days|contains(1)}selected="selected"{/section}>{'Monday'|i18n( 'ezchat/datatypes/chatroom' )}</option>
							<option value="2" {section show=$days|contains(2)}selected="selected"{/section}>{'Tuesday'|i18n( 'ezchat/datatypes/chatroom' )}</option>
							<option value="3" {section show=$days|contains(3)}selected="selected"{/section}>{'Wednesday'|i18n( 'ezchat/datatypes/chatroom' )}</option>
							<option value="4" {section show=$days|contains(4)}selected="selected"{/section}>{'Tursday'|i18n( 'ezchat/datatypes/chatroom' )}</option>
							<option value="5" {section show=$days|contains(5)}selected="selected"{/section}>{'Friday'|i18n( 'ezchat/datatypes/chatroom' )}</option>
							<option value="6" {section show=$days|contains(6)}selected="selected"{/section}>{'Saturday'|i18n( 'ezchat/datatypes/chatroom' )}</option>
						</select>
					</td>
					<td>
						<div class="element">
							<label>
								<input id="ezcoa-{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}" class="ezcc-{$attribute.object.content_class.identifier} ezcca-{$attribute.object.content_class.identifier}_{$attribute.contentclass_attribute_identifier}" type="checkbox" name="{$attribute_base}_ezchatroom_allowprivatemessages_boolean_{$attribute.id}" {$attribute.content.option_list.0.value|choose( '', 'checked="checked"' )} value="" />{'Allow private messages'|i18n( 'ezchat/datatypes/chatroom' )}
							</label>
						</div>
						<div class="element">
							<label>
								<input id="ezcoa-{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}" class="ezcc-{$attribute.object.content_class.identifier} ezcca-{$attribute.object.content_class.identifier}_{$attribute.contentclass_attribute_identifier}" type="checkbox" name="{$attribute_base}_ezchatroom_showchannelmessages_boolean_{$attribute.id}" {$attribute.content.option_list.1.value|choose( '', 'checked="checked"' )} value="" />{'Show channel messages'|i18n( 'ezchat/datatypes/chatroom' )}
							</label>
						</div>
						<div class="element">
							<label>
								<input id="ezcoa-{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}" class="ezcc-{$attribute.object.content_class.identifier} ezcca-{$attribute.object.content_class.identifier}_{$attribute.contentclass_attribute_identifier}" type="checkbox" name="{$attribute_base}_ezchatroom_requestmessagespriorchannelenter_boolean_{$attribute.id}" {$attribute.content.option_list.2.value|choose( '', 'checked="checked"' )} value="" />{'Request messages prior channel enter'|i18n( 'ezchat/datatypes/chatroom' )}
							</label>
						</div>
					</td>
				</tr>
			</tbody>
		</table>

		<div class="break"></div>

		<div class="element">
			<label>
				<input id="ezcoa-{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}" class="ezcc-{$attribute.object.content_class.identifier} ezcca-{$attribute.object.content_class.identifier}_{$attribute.contentclass_attribute_identifier}" type="checkbox" name="{$attribute_base}_ezchatroom_deactivateGMaps_boolean_{$attribute.id}" {$attribute.content.option_list.4.value|choose( '', 'checked="checked"' )} value="" />{'Deactivate Google Maps tools'|i18n( 'ezchat/datatypes/chatroom' )}
			</label>
		</div>

	</div>

</fieldset>
</div>

{/let}
{/let}{/let}
{/default}
