{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{*
 SOFTWARE NAME: eZchat
 SOFTWARE RELEASE: 0.1.x
 COPYRIGHT NOTICE: Copyright (C) 2008 Xavier GOULEY & Maxime THOMAS
 SOFTWARE LICENSE: GNU General Public License v2.0
 NOTICE: >
   This program is free software; you can redistribute it and/or
   modify it under the terms of version 2.0  of the GNU General
   Public License as published by the Free Software Foundation.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of version 2.0 of the GNU General
   Public License along with this program; if not, write to the Free
   Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
   MA 02110-1301, USA.
*}

{set-block scope=root variable=cache_ttl}0{/set-block}

{def $currentUser = fetch( 'user', 'current_user' )}


<script src="{ezroot(no)}extension/ezchat/ajaxchat/js/chat.js" type="text/javascript" charset="UTF-8"></script>
<script src="{ezroot(no)}extension/ezchat/ajaxchat/js/lang/[LANG_CODE/].js" type="text/javascript" charset="UTF-8"></script>
<script src="{ezroot(no)}extension/ezchat/ajaxchat/js/config.js" type="text/javascript" charset="UTF-8"></script>
<script type="text/javascript">
	// <![CDATA[
		function initializeLoginPage() {ldelim}
			document.getElementById('userNameField').focus();
			if(!ajaxChat.isCookieEnabled()) {ldelim}
				var node = document.createElement('div');
				var text = document.createTextNode(ajaxChatLang['errorCookiesRequired']);
				node.appendChild(text);
				document.getElementById('errorContainer').appendChild(node);
			{rdelim}
		{rdelim}
		ajaxChatConfig.sessionName = '[SESSION_NAME/]';
		ajaxChatConfig.cookieExpiration = parseInt('[COOKIE_EXPIRATION/]');
		ajaxChatConfig.cookiePath = '[COOKIE_PATH/]';
		ajaxChatConfig.cookieDomain = '[COOKIE_DOMAIN/]';
		ajaxChatConfig.cookieSecure = '[COOKIE_SECURE/]';
		ajaxChat.init(ajaxChatConfig, ajaxChatLang, false, true, false);
	// ]]>
</script>

<div class="border-box">
	<div class="border-tl"><div class="border-tr"><div class="border-tc"></div></div></div>
	<div class="border-ml"><div class="border-mr"><div class="border-mc float-break">
	<div class="content-view-full">



					<div class="maincontentheader">
						<h1>{'Chatroom access'|i18n( 'design/standard/ezchat' )}</h1>
					</div>

					<noscript>
					<div class="warning">
					<h2>[LANG]requiresJavaScript[/LANG]</h2>
					<ul>
					    <li>{"Javascript capabilities are required to enter this chatroom."|i18n("design/standard/user")}</li>
					</ul>
					</div>
					</noscript>

					<div class="block"><div id="errorContainer">[ERROR_MESSAGES/]</div></div>

					<div class="break"></div>



					{* LoggedOut case : just a button to login back *}
					{if $logout|and($currentUser.login|ne('anonymous'))}
						<div class="attribute-long">
							{'You just sign out from chatroom. You can login back or logout from site.'|i18n("design/standard/user")}
						</div>
						<div class="break"></div>
						<div class="LoginBackBox">
							<form id="loginForm" action={$loginURL|ezurl()} method="post" enctype="application/x-www-form-urlencoded">
								<h2>{"Sign in back"|i18n("design/standard/ezchat")}</h2>
								<div class="buttonblock">
									<input type="hidden" name="userName" id="userNameField" value="{$currentUser.login}" />
									<input type="hidden" name="password" id="passwordField" value ="fomodepass104326547865" />
									<input type="hidden" name="channelName" id="channelField" value="{$channel}" />
									<input id="languageSelection" name="lang" value="{$langDefault}" type="hidden" />
									<input class="defaultbutton" type="submit" name="submit" id="loginButton" value="{'Sign in back'|i18n('design/standard/ezchat','Button')}" tabindex="1" />
								</div>
							</form>
						</div>
						<div class="LogoutBox">
							<form id="loginForm" action="{$loginURL|ezurl(no)}?logout=full" method="post">
								<h2>{"Logout"|i18n("design/standard/ezchat")}</h2>
								<div class="buttonblock">
									<input class="defaultbutton" type="submit" name="submit" id="logoutButton" value="{'Logout'|i18n('design/standard/ezchat','Button')}" tabindex="1" />
								</div>
							</form>
						</div>


					{* anonymous case : type a guest username and connect *}
					{elseif $currentUser.login|eq('anonymous')}
						<div class="attribute-long">
							{'You are currently not logged in. You can use a registered account and login, or enter chat room as a guest user.'|i18n("design/standard/user")}
						</div>
						<div class="break"></div>

	</div>
	</div></div></div>
	<div class="border-bl"><div class="border-br"><div class="border-bc"></div></div></div>
</div>
<div class="border-box signinContainer">
	<div class="border-tl"><div class="border-tr"><div class="border-tc"></div></div></div>
	<div class="border-ml"><div class="border-mr"><div class="border-mc float-break">
	<div class="content-view-full">

						<div class="SignInBox">
							<form id="loginForm" action={$loginURL|ezurl()} method="post" enctype="application/x-www-form-urlencoded">
								<h2>{"Sign in as a guest"|i18n("design/standard/ezchat")}</h2>
								<div class="block">
									<label for="userNameField">{"Guest nickname"|i18n("design/standard/ezchat")}</label><div class="labelbreak"></div>
									<input class="box" type="text" name="userName" id="userNameField" maxlength="[USER_NAME_MAX_LENGTH/]" size="10" tabindex="1" />
								</div>
								<div class="buttonblock">
									<input type="hidden" name="password" id="passwordField" value ="" />
									<input type="hidden" name="channelName" id="channelField" value="{$channel}" />
									<input id="languageSelection" name="lang" value="{$langDefault}" type="hidden" />
									<input class="defaultbutton" type="submit" name="submit" id="loginButton" value="{'Sign in'|i18n('design/standard/ezchat','Button')}" tabindex="1" />
								</div>
							</form>
							<div xclass="break"></div>
							<!--
								Please retain the full copyright notice below including the link to blueimp.net.
								This not only gives respect to the amount of time given freely by the developer
								but also helps build interest, traffic and use of AJAX Chat.

								Thanks,
								Sebastian Tschan
							//-->
							<div class="chatCopyright"><a href="https://blueimp.net/ajax/">AJAX Chat</a> &copy; <a href="https://blueimp.net">blueimp.net</a></div>
						</div>

	</div>
	</div></div></div>
	<div class="border-bl"><div class="border-br"><div class="border-bc"></div></div></div>
</div>
<div class="border-box loginContainer">
	<div class="border-tl"><div class="border-tr"><div class="border-tc"></div></div></div>
	<div class="border-ml"><div class="border-mr"><div class="border-mc float-break">
	<div class="content-view-full">

						<div class="LoginBox">
							<form method="post" action={"/user/login/"|ezurl()}>
								<h2>{"Login"|i18n("design/standard/user")}</h2>
								<div class="block">
									<label for="id1">{"Username"|i18n("design/standard/user",'User name')}</label><div class="labelbreak"></div>
									<input class="box" type="text" size="10" name="Login" id="id1" value="{$User:login|wash}" tabindex="1" />
								</div>
								<div class="block">
									<label for="id2">{"Password"|i18n("design/standard/user")}</label><div class="labelbreak"></div>
									<input class="box" type="password" size="10" name="Password" id="id2" value="" tabindex="1" />
								</div>
								{if and( ezini_hasvariable( 'Session', 'RememberMeTimeout' ), ezini( 'Session', 'RememberMeTimeout' ) )}
								    <div class="block">
								        <input type="checkbox" tabindex="1" name="Cookie" id="id3" /><label for="id3" style="display:inline;">{"Remember me"|i18n("design/admin/user/login")}</label>
								    </div>
								{/if}
								<div class="buttonblock">
									<input class="defaultbutton" type="submit" name="LoginButton" value="{'Login'|i18n('design/standard/user','Button')}" tabindex="1" />
									<input class="button" type="submit" name="RegisterButton" value="{'Sign Up'|i18n('design/standard/user','Button')}" tabindex="1" />
								</div>
								{section show=ezini( 'SiteSettings', 'LoginPage' )|eq( 'custom' )}
								    <p><a href={'/user/forgotpassword'|ezurl}>{'Forgot your password?'|i18n( 'design/standard/user' )}</a></p>
								{/section}

								<input type="hidden" name="RedirectURI" value={$loginURL} />

								{section show=and( is_set( $User:post_data ), is_array( $User:post_data ) )}
								  {section name=postData loop=$User:post_data }
								     <input name="Last_{$postData:key}" value="{$postData:item}" type="hidden" /><br/>
								  {/section}
								{/section}
							</form>
						</div>
					{/if}

					<div class="break"></div>

	</div>
	</div></div></div>
	<div class="border-bl"><div class="border-br"><div class="border-bc"></div></div></div>
</div>

<script type="text/javascript">
	// <![CDATA[
		window.onload="initializeLoginPage";
	// ]]>
</script>

