{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{*
 SOFTWARE NAME: eZchat
 SOFTWARE RELEASE: 0.1.x
 COPYRIGHT NOTICE: Copyright (C) 2008 Xavier GOULEY & Maxime THOMAS
 SOFTWARE LICENSE: GNU General Public License v2.0
 NOTICE: >
   This program is free software; you can redistribute it and/or
   modify it under the terms of version 2.0  of the GNU General
   Public License as published by the Free Software Foundation.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of version 2.0 of the GNU General
   Public License along with this program; if not, write to the Free
   Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
   MA 02110-1301, USA.
*}

{set-block scope=root variable=cache_ttl}0{/set-block}
{default gMapsInterface=false()}


<script src="{ezroot(no)}extension/ezchat/ajaxchat/js/chat.js" type="text/javascript" charset="UTF-8"></script>
<script src="{'javascript/custom.js'|ezdesign(no)}" type="text/javascript" charset="UTF-8"></script>
<script src="{ezroot(no)}extension/ezchat/ajaxchat/js/lang/[LANG_CODE/].js" type="text/javascript" charset="UTF-8"></script>
<script src="{ezroot(no)}extension/ezchat/ajaxchat/js/config.js" type="text/javascript" charset="UTF-8"></script>
<script src="{ezroot(no)}extension/ezchat/ajaxchat/js/FABridge.js" type="text/javascript" charset="UTF-8"></script>
<script type="text/javascript">
	// <![CDATA[
		function toggleContainer(containerID, hideContainerIDs) {ldelim}
			if(hideContainerIDs) {ldelim}
				for(var i=0; i<hideContainerIDs.length; i++) {ldelim}
					ajaxChat.showHide(hideContainerIDs[i], 'none');
				{rdelim}
			{rdelim}
			ajaxChat.showHide(containerID);
			if(typeof arguments.callee.styleProperty == 'undefined') {ldelim}
				if(typeof isIElt7 != 'undefined') {ldelim}
					arguments.callee.styleProperty = 'marginRight';
				{rdelim} else {ldelim}
					arguments.callee.styleProperty = 'right';
				{rdelim}
			{rdelim}
			var containerWidth = document.getElementById(containerID).offsetWidth;
			if(containerWidth) {ldelim}
				document.getElementById('chatList').style[arguments.callee.styleProperty] = (containerWidth+28)+'px';
			{rdelim} else {ldelim}
				document.getElementById('chatList').style[arguments.callee.styleProperty] = '20px';
			{rdelim}
		{rdelim}

		function initialize() {ldelim}
			if(ajaxChat.getSetting('onlineList') === false) {ldelim}
				toggleContainer('onlineListContainer');
			{rdelim}
			ajaxChat.updateButton('audio', 'audioButton');
			ajaxChat.updateButton('autoScroll', 'autoScrollButton');
			{*
			document.getElementById('bbCodeSetting').checked = ajaxChat.getSetting('bbCode');
			document.getElementById('hyperLinksSetting').checked = ajaxChat.getSetting('hyperLinks');
			document.getElementById('lineBreaksSetting').checked = ajaxChat.getSetting('lineBreaks');
			document.getElementById('emoticonsSetting').checked = ajaxChat.getSetting('emoticons');
			document.getElementById('autoFocusSetting').checked = ajaxChat.getSetting('autoFocus');
			document.getElementById('maxMessagesSetting').value = ajaxChat.getSetting('maxMessages');
			document.getElementById('wordWrapSetting').checked = ajaxChat.getSetting('wordWrap');
			document.getElementById('maxWordLengthSetting').value = ajaxChat.getSetting('maxWordLength');
			document.getElementById('dateFormatSetting').value = ajaxChat.getSetting('dateFormat');
			document.getElementById('persistFontColorSetting').checked = ajaxChat.getSetting('persistFontColor');
			for(var i=0; i<document.getElementById('audioVolumeSetting').options.length; i++) {ldelim}
				if(document.getElementById('audioVolumeSetting').options[i].value == ajaxChat.getSetting('audioVolume')) {ldelim}
					document.getElementById('audioVolumeSetting').options[i].selected = true;
					break;
				{rdelim}
			{rdelim}
			ajaxChat.fillSoundSelection('soundReceiveSetting', ajaxChat.getSetting('soundReceive'));
			ajaxChat.fillSoundSelection('soundSendSetting', ajaxChat.getSetting('soundSend'));
			ajaxChat.fillSoundSelection('soundEnterSetting', ajaxChat.getSetting('soundEnter'));
			ajaxChat.fillSoundSelection('soundLeaveSetting', ajaxChat.getSetting('soundLeave'));
			ajaxChat.fillSoundSelection('soundChatBotSetting', ajaxChat.getSetting('soundChatBot'));
			ajaxChat.fillSoundSelection('soundErrorSetting', ajaxChat.getSetting('soundError'));
			document.getElementById('blinkSetting').checked = ajaxChat.getSetting('blink');
			document.getElementById('blinkIntervalSetting').value = ajaxChat.getSetting('blinkInterval');
			document.getElementById('blinkIntervalNumberSetting').value = ajaxChat.getSetting('blinkIntervalNumber');
			*}
		{rdelim}

		function finalize() {ldelim}
			ajaxChat.setSetting('onlineList', (document.getElementById('onlineListContainer').offsetWidth > 0));
		{rdelim}

		{if $gMapsInterface}
			{def $defaultStartingLocationLat=first_set($startingLocationLat, ezini( 'gmapsSettings', 'defaultStartingLocationLat', 'ezchat.ini' ))}
			{def $defaultStartingLocationLng=first_set($startingLocationLng, ezini( 'gmapsSettings', 'defaultStartingLocationLng', 'ezchat.ini' ))}
			{def $defaultStartingLocationZoom=first_set($startingLocationZoom, ezini( 'gmapsSettings', 'defaultStartingLocationZoom', 'ezchat.ini' ))}

			var gmapLoaded = false;
			function loadGoogleMap() {ldelim}
				ajaxChat.toggleSetting('help', 'gMapsButton');
				toggleContainer('gmap-box', '');
				if (gmapLoaded == false) {ldelim}
					try {ldelim}
						initGoogleMap(gmapInitLatitude, gmapInitLongitude, gmapInitZoom);
					{rdelim} catch(e) {ldelim}
						initGoogleMap({$defaultStartingLocationLat},{$defaultStartingLocationLng},{$defaultStartingLocationZoom});
					{rdelim}
					gmapLoaded = true;
				{rdelim}
			{rdelim}

			{undef $defaultStartingLocationLat $defaultStartingLocationLng $defaultStartingLocationZoom}
		{/if}

		ajaxChatConfig.loginChannelID = parseInt('[LOGIN_CHANNEL_ID/]');
		ajaxChatConfig.sessionName = '[SESSION_NAME/]';
		ajaxChatConfig.cookieExpiration = parseInt('[COOKIE_EXPIRATION/]');
		ajaxChatConfig.cookiePath = '[COOKIE_PATH/]';
		ajaxChatConfig.cookieDomain = '[COOKIE_DOMAIN/]';
		ajaxChatConfig.cookieSecure = '[COOKIE_SECURE/]';
		ajaxChatConfig.chatBotName = decodeURIComponent('[CHAT_BOT_NAME/]');
		ajaxChatConfig.chatBotID = '[CHAT_BOT_ID/]';
		ajaxChatConfig.allowUserMessageDelete = parseInt('[ALLOW_USER_MESSAGE_DELETE/]');
		ajaxChatConfig.inactiveTimeout = parseInt('[INACTIVE_TIMEOUT/]');
		ajaxChatConfig.privateChannelDiff = parseInt('[PRIVATE_CHANNEL_DIFF/]');
		ajaxChatConfig.privateMessageDiff = parseInt('[PRIVATE_MESSAGE_DIFF/]');
		ajaxChatConfig.showChannelMessages = parseInt('[SHOW_CHANNEL_MESSAGES/]');
		ajaxChatConfig.messageTextMaxLength = parseInt('[MESSAGE_TEXT_MAX_LENGTH/]');
		ajaxChatConfig.socketServerEnabled = parseInt('[SOCKET_SERVER_ENABLED/]');
		ajaxChatConfig.socketServerHost = decodeURIComponent('[SOCKET_SERVER_HOST/]');
		ajaxChatConfig.socketServerPort = parseInt('[SOCKET_SERVER_PORT/]');
		ajaxChatConfig.socketServerChatID = parseInt('[SOCKET_SERVER_CHAT_ID/]');
		ajaxChatConfig.ajaxURL = "{$loginURL|ezurl(no)}?ajax=true";
		ajaxChat.ajaxURL = "{$loginURL|ezurl(no)}?ajax=true";
 		ajaxChatConfig.baseURL = "{ezroot(no)}extension/ezchat/ajaxchat/";
		ajaxChat.init(ajaxChatConfig, ajaxChatLang, true, true, true, initialize, finalize);
		ajaxChat.lang['callUserPicture'] = "{'Show picture'|i18n('design/standard/ezchat')}";
		ezChat.baseURL = "{'/'|ezurl(no)}";
		{if $gMapsInterface}
			ezChat.strMapSent = "{'%1 shows a point on the map: '|i18n('design/standard/ezchat','',array('<span dir=\'ltr\' onclick=\'ajaxChat.insertText(this.firstChild.nodeValue);\'>%s</span>'))}"+ezChat.strMapSent;
		{else}
			ezChat.strMapSent = "{'%1 shows a point on the map: '|i18n('design/standard/ezchat','',array('<span dir=\'ltr\' onclick=\'ajaxChat.insertText(this.firstChild.nodeValue);\'>%s</span>'))}<a href=\"javascript:alert('{'This functionality is disabled for this moment.'|i18n('design/standard/ezchat')}');\">%c</a>";
		{/if}
	// ]]>
</script>


<div style="float:left;width:70%;">
	<div class="border-box">
	<div class="border-tl"><div class="border-tr"><div class="border-tc"></div></div></div>
	<div class="border-ml"><div class="border-mr"><div class="border-mc float-break">
	<div class="content-view-full">

			<div class="maincontentheader">
				<h1>[LANG]title[/LANG]</h1>
			</div>
			<div class="chatBlock">
				<div id="chatList"></div>
				<div id="submitButtonContainer" class="buttonblock">
					<span id="messageLengthCounter">0/[MESSAGE_TEXT_MAX_LENGTH/]</span><br/>
					<input class="defaultbutton" type="button" id="submitButton" value="[LANG]messageSubmit[/LANG]" onclick="ajaxChat.sendMessage();"/>
				</div>
				<div id="inputFieldContainer">
					<textarea id="inputField" rows="2" wrap="soft" title="[LANG]inputLineBreak[/LANG]" onkeypress="ajaxChat.handleInputFieldKeyPress(event);" onkeyup="ajaxChat.handleInputFieldKeyUp(event);"></textarea>
				</div>
				<div class="break"></div>
				<div id="emoticonsContainer" dir="ltr"></div>
				<div class="break"></div>
				<div id="bbCodeContainer">
					<input class="defaultbutton" type="button" value="[LANG]bbCodeLabelBold[/LANG]" title="[LANG]bbCodeTitleBold[/LANG]" onclick="ajaxChat.insertBBCode('b');"/>
					<input class="defaultbutton" type="button" value="[LANG]bbCodeLabelItalic[/LANG]" title="[LANG]bbCodeTitleItalic[/LANG]" onclick="ajaxChat.insertBBCode('i');"/>
					<input class="defaultbutton" type="button" value="[LANG]bbCodeLabelUnderline[/LANG]" title="[LANG]bbCodeTitleUnderline[/LANG]" onclick="ajaxChat.insertBBCode('u');"/>
					<input class="defaultbutton" type="button" value="[LANG]bbCodeLabelQuote[/LANG]" title="[LANG]bbCodeTitleQuote[/LANG]" onclick="ajaxChat.insertBBCode('quote');"/>
					<input class="defaultbutton" type="button" value="[LANG]bbCodeLabelCode[/LANG]" title="[LANG]bbCodeTitleCode[/LANG]" onclick="ajaxChat.insertBBCode('code');"/>
					<input class="defaultbutton" type="button" value="[LANG]bbCodeLabelURL[/LANG]" title="[LANG]bbCodeTitleURL[/LANG]" onclick="ajaxChat.insertBBCode('url');"/>
					<input class="defaultbutton" type="button" value="[LANG]bbCodeLabelColor[/LANG]" title="[LANG]bbCodeTitleColor[/LANG]" onclick="ajaxChat.showHide('colorCodesContainer', null);"/>
					<input type="button" class="defaultbutton" id="audioButton" value="[LANG]toggleAudio[/LANG]" title="[LANG]toggleAudio[/LANG]" onclick="ajaxChat.toggleSetting('audio', 'audioButton');"/>
					<input type="button" class="defaultbutton" id="autoScrollButton" value="[LANG]toggleAutoScroll[/LANG]" title="[LANG]toggleAutoScroll[/LANG]" onclick="ajaxChat.toggleSetting('autoScroll', 'autoScrollButton');"/>
				</div>
				<div id="colorCodesContainer" style="display:none;" dir="ltr"></div>
		  		<div class="break"></div>
		  	</div>

	</div>
	</div></div></div>
	<div class="border-bl"><div class="border-br"><div class="border-bc"></div></div></div>
	</div>

	{* GoogleMaps interface: *}
	{if $gMapsInterface}
		<div class="border-box" id="gmap-box" style="display:none;">
		<div class="border-tl"><div class="border-tr"><div class="border-tc"></div></div></div>
		<div class="border-ml"><div class="border-mr"><div class="border-mc float-break low-padding">
		<div class="content-view-full">
			{include uri="design:ezchat/gmaps.tpl"}
		</div>
		</div></div></div>
		<div class="border-bl"><div class="border-br"><div class="border-bc"></div></div></div>
		</div>
	{/if}


</div>
<div style="float:right;width:30%;">
	<div class="border-box">
	<div class="border-tl"><div class="border-tr"><div class="border-tc"></div></div></div>
	<div class="border-ml"><div class="border-mr"><div class="border-mc" style="padding:0pt;">
	<div class="border-content">
		<div class="block-type-3items block-view-3_items1">
			<div class="attribute-header"><h2>[LANG]channel[/LANG]</h2></div>
			<div id="logoutChannelContainer" class="buttonblock">
				<div style="float:right;">
					<a href="javascript:loadGoogleMap();" title="{'Toggle Google Maps'|i18n('design/standard/ezchat')}"><img src={'gmaps/map_compass.png'|ezimage} width="48" height="48" border="0" /></a>
				</div>
				<div class="defaultselect">
					<select onchange="ajaxChat.switchChannel(this.options[this.selectedIndex].value);">[CHANNEL_OPTIONS/]</select>
				</div>
				<div class="block-separator"></div>
				<input class="defaultbutton" type="button" id="logoutButton" value="{'Sign out from channel'|i18n('design/standard/ezchat','Button')}" onclick="ajaxChat.logout();"/>
	  		</div>
	  	</div>
		<div class="block-separator"></div>

	    <!-- BLOCK: START -->
		<div class="block-type-itemlist">
			<div class="attribute-header"><a href="#" title="[LANG]toggleOnlineList[/LANG]" onclick="toggleContainer('onlineListContainer', new Array('settingsContainer','helpContainer'));">
			    <h2>[LANG]onlineUsers[/LANG]</h2>
			</a></div>
			<div class="block-content" id="onlineListContainer">
			    <div id="onlineList"></div>
			</div>
		</div>
		<!-- BLOCK: END -->

		<!-- BLOCK: START -->
		<div class="block-type-itemlist" id="helpTopContainer">
			<div class="attribute-header"><a href="#" title="[LANG]toggleHelp[/LANG]" onclick="toggleContainer('helpContainer', new Array('onlineListContainer','settingsContainer'));">
			    <h2>[LANG]help[/LANG]</h2>
			</a></div>
			<div class="block-content" id="helpContainer" style="display:none;">
			    <div id="helpList">
					<table>
						<tr class="rowOdd">
							<td class="desc">[LANG]helpItemDescJoin[/LANG]</td>
							<td class="code">[LANG]helpItemCodeJoin[/LANG]</td>
						</tr>
						<tr class="rowEven">
							<td class="desc">[LANG]helpItemDescJoinCreate[/LANG]</td>
							<td class="code">[LANG]helpItemCodeJoinCreate[/LANG]</td>

						</tr>
						<tr class="rowOdd">
							<td class="desc">[LANG]helpItemDescInvite[/LANG]</td>
							<td class="code">[LANG]helpItemCodeInvite[/LANG]</td>
						</tr>
						<tr class="rowEven">
							<td class="desc">[LANG]helpItemDescUninvite[/LANG]</td>
							<td class="code">[LANG]helpItemCodeUninvite[/LANG]</td>
						</tr>

						<tr class="rowOdd">
							<td class="desc">[LANG]helpItemDescLogout[/LANG]</td>
							<td class="code">[LANG]helpItemCodeLogout[/LANG]</td>
						</tr>
						<tr class="rowEven">
							<td class="desc">[LANG]helpItemDescPrivateMessage[/LANG]</td>
							<td class="code">[LANG]helpItemCodePrivateMessage[/LANG]</td>
						</tr>
						<tr class="rowOdd">

							<td class="desc">[LANG]helpItemDescQueryOpen[/LANG]</td>
							<td class="code">[LANG]helpItemCodeQueryOpen[/LANG]</td>
						</tr>
						<tr class="rowEven">
							<td class="desc">[LANG]helpItemDescQueryClose[/LANG]</td>
							<td class="code">[LANG]helpItemCodeQueryClose[/LANG]</td>
						</tr>
						<tr class="rowOdd">
							<td class="desc">[LANG]helpItemDescAction[/LANG]</td>
							<td class="code">[LANG]helpItemCodeAction[/LANG]</td>
						</tr>
						<tr class="rowEven">
							<td class="desc">[LANG]helpItemDescDescribe[/LANG]</td>
							<td class="code">[LANG]helpItemCodeDescribe[/LANG]</td>
						</tr>
						<tr class="rowOdd">
							<td class="desc">[LANG]helpItemDescIgnore[/LANG]</td>
							<td class="code">[LANG]helpItemCodeIgnore[/LANG]</td>

						</tr>
						<tr class="rowEven">
							<td class="desc">[LANG]helpItemDescIgnoreList[/LANG]</td>
							<td class="code">[LANG]helpItemCodeIgnoreList[/LANG]</td>
						</tr>
						<tr class="rowOdd">
							<td class="desc">[LANG]helpItemDescWhereis[/LANG]</td>
							<td class="code">[LANG]helpItemCodeWhereis[/LANG]</td>
						</tr>

						<tr class="rowEven">
							<td class="desc">[LANG]helpItemDescKick[/LANG]</td>
							<td class="code">[LANG]helpItemCodeKick[/LANG]</td>
						</tr>
						<tr class="rowOdd">
							<td class="desc">[LANG]helpItemDescUnban[/LANG]</td>
							<td class="code">[LANG]helpItemCodeUnban[/LANG]</td>
						</tr>
						<tr class="rowEven">

							<td class="desc">[LANG]helpItemDescBans[/LANG]</td>
							<td class="code">[LANG]helpItemCodeBans[/LANG]</td>
						</tr>
						<tr class="rowOdd">
							<td class="desc">[LANG]helpItemDescWhois[/LANG]</td>
							<td class="code">[LANG]helpItemCodeWhois[/LANG]</td>
						</tr>
						<tr class="rowEven">
							<td class="desc">[LANG]helpItemDescWho[/LANG]</td>

							<td class="code">[LANG]helpItemCodeWho[/LANG]</td>
						</tr>
						<tr class="rowOdd">
							<td class="desc">[LANG]helpItemDescList[/LANG]</td>
							<td class="code">[LANG]helpItemCodeList[/LANG]</td>
						</tr>
						<tr class="rowEven">
							<td class="desc">[LANG]helpItemDescRoll[/LANG]</td>
							<td class="code">[LANG]helpItemCodeRoll[/LANG]</td>

						</tr>
						<tr class="rowOdd">
							<td class="desc">[LANG]helpItemDescNick[/LANG]</td>
							<td class="code">[LANG]helpItemCodeNick[/LANG]</td>
						</tr>
					</table>
				</div>
			</div>
		</div>
		<!-- BLOCK: END -->

		<div class="block-separator"></div>
		<!--
			Please retain the full copyright notice below including the link to blueimp.net.
			This not only gives respect to the amount of time given freely by the developer
			but also helps build interest, traffic and use of AJAX Chat.

			Thanks,
			Sebastian Tschan
		//-->
		<div class="chatCopyright"><a href="https://blueimp.net/ajax/">AJAX Chat</a> &copy; <a href="https://blueimp.net">blueimp.net</a></div>
	</div></div>
	</div></div></div>
	<div class="border-bl"><div class="border-br"><div class="border-bc"></div></div></div>
</div>
<div id="flashInterfaceContainer"></div>

{/default}